export const contents = [
  {
    title1: "원하는 링크를",
    title2: "저장",
    title3: "하세요",
    description1: "나중에 읽고 싶은 글, 다시 보고 싶은 영상,",
    description2: "사고 싶은 옷, 기억하고 싶은 모든 것을",
    description3: "한 공간에 저장하세요.",
    src: "/images/image1.png",
    alt: "링크 설명 이미지",
    gradient: "gradient1",
  },
  {
    title1: "링크를 폴더로",
    title2: "관리",
    title3: "하세요",
    description1: "나만의 폴더를 무제한으로 만들고",
    description2: "다양하게 활용할 수 있습니다.",
    description3: "",
    src: "./images/image2.png",
    alt: "링크 관리 설명 이미지",
    gradient: "gradient2",
  },
  {
    title1: "저장한 링크를",
    title2: "공유",
    title3: "해보세요",
    description1: "여러 링크를 폴더에 담고 공유할 수 있습니다.",
    description2: "가족, 친구, 동료들에게 쉽고 빠르게 링크를",
    description3: "공유해 보세요.",
    src: "./images/image3.png",
    alt: "링크 공유 설명 이미지",
    gradient: "gradient3",
  },
  {
    title1: "저장한 링크를",
    title2: "검색",
    title3: "해보세요",
    description1: "중요한 정보들을 검색으로 쉽게 찾아보세요.",
    description2: "",
    description3: "",
    src: "/images/image4.png",
    alt: "링크 검색 설명 이미지",
    gradient: "gradient4",
  },
];
